config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create
#                     root GET    /                              items#index
#              delete_item GET    /items/:id/delete(.:format)    items#delete
#                    items GET    /items(.:format)               items#index
#                          POST   /items(.:format)               items#create
#                 new_item GET    /items/new(.:format)           items#new
#                edit_item GET    /items/:id/edit(.:format)      items#edit
#                     item GET    /items/:id(.:format)           items#show
#                          PATCH  /items/:id(.:format)           items#update
#                          PUT    /items/:id(.:format)           items#update
#                          DELETE /items/:id(.:format)           items#destroy
#

Rails.application.routes.draw do

  devise_for :users
  root 'items#index'

  resources :items do
    member do
      get :delete
    end
    resources :item_loans, shallow: true
  end

  resources :item_loans

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id               :integer          not null, primary key
#  name             :string           not null
#  item_type        :string           not null
#  item_description :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :integer
#  image            :string
#

class Item < ApplicationRecord

  belongs_to :user
  has_many :item_loans

  mount_uploader :image, ImageUploader

  validates :name,            presence: true,
                              length: {within: 3..50}

  validates :item_type,       presence: true,
                              length: {within: 3..25}

  scope :sorted, -> {order('name ASC')
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :count_items, only: [:index]
  before_action :item_owner?, only: [:edit]
  before_action :authenticate_user!, except: [:index]

  def index
    @items = Item.sorted.paginate(page: params[:page], per_page: 10)
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_basic_params)
    if @item.save
      flash[:notice] = "#{@item.name} Successfully created"
      redirect_to items_path
    else
      flash.now[:alert] = @item.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_basic_params)
      flash[:notice] = "#{@item.name} Successfully Update"
      redirect_to (item_path(@item))
    else
      flash[:alert] = "Error updating"
      render 'edit'
    end
  end

  def delete
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "#{@item.name} Deleted Successfully"
    redirect_to items_path
  end

  private

  def item_basic_params
    params.require(:item).permit(:user_id, :name, :item_type, :item_description, :image)
  end

  def count_items
    @total_items = Item.all.count
  end

  def item_owner?
    @item = Item.find(params[:id])
    unless user_signed_in? && @item.user_id == current_user.id
      flash[:notice] = "You do not own this item"
      render 'show'
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def options_for_select
    %w(Tool Pump)
  end

  def avalible?(item)
    if item.item_loans.owner_confirmed_loan == false && item.item_loans.owner_confirmed_loan_returned != false
      link_to 'Request Item', item_loans_new_path(item)
    else
      "Item loaned"
    end 
  end
end

app/views/items/_form.html.erb
  <%= link_to '<i class="arrow left icon"></i>Items'.html_safe, items_path %>

  <%= form_for @item, html: {class: 'ui form', multipart: true} do |f| %>

    <h4 class="ui dividing header"><%= @title %></h4>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image%>
    </div>

    <div class="required field">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'Item' %>
    </div>

    <div class="field">
      <%= f.label :item_type %>
      <%= f.select :item_type, options_for_select, {},{class: 'ui simple dropdown item'} %>
    </div>

    <div class="field">
      <%= f.label :item_description %>
      <%= f.text_area :item_description, placeholder: 'Short description' %>
    </div>

    <%= f.button 'Submit', class: 'ui button', data: {disable_with: "<div class='ui active tiny inline loader'></div> Creating"} %>

  <% end %>

app/views/items/delete.html.erb
<div class="delete-page">
  <h2>Delete <%= @item.name %></h2>

  <%= link_to '<i class="arrow left icon"></i>Items'.html_safe, items_path %>
  <br/>
  <br/>

  <p>Are you sure you want to delete this item?</p>

  <%= form_for @item, method: 'delete' do |f| %>

  <% f.submit 'Delete', class: 'ui negative button' %>
  <% end  %>
</div>

app/views/items/edit.html.erb
<% @title = 'Edit Item' %>
<div class="new-page">
  <h2>Edit Item</h2>
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
<div class="index-page">
  <h2>Listed Items</h2>
  <h4><%= @total_items %> items in Database</h4>
  <%= link_to '<i class="add circle icon"></i>New Item'.html_safe, new_item_path, class: 'new-link' %>
  <table id="index" class="ui table">
    <thead>
      <tr>
        <th>Thumbnail</th>
        <th>Name</th>
        <th>Type</th>
        <th>Owner</th>
        <th>Description</th>
        <th>Avalible to Borrow</th>
        <th>Options</th>
      </tr>
    </thead>
    <% @items.each do |item| %>
    <tr>
      <td><%= has_image?(item) %></td>
      <td><%= item.name %></td>
      <td><%= item.item_type %></td>
      <td><%= item.user.username %></td>
      <td><%= item.item_description %></td>
      <td><%= link_to 'Request Loan', new_item_item_loan_path(item, @item_loan) %></td>
      <td>

        <%= link_to 'Show', item_path(item), class: 'ui primary basic button'%>
      </td>
    </tr>
    <% end %>
    <tfoot>
      <tr>
        <th colspan="7">
          <%= will_paginate @items, renderer: WillPaginateSemanticUi::ActionView::Renderer, class: 'right floated', inner_window: '1', outer_window: '0' %>
        </th>
      </tr>
    </tfoot>
  </table>

</div>

app/views/items/new.html.erb
<% @title = 'New Item' %>
<div class="new-page">
  <h2>List New Item</h2>
  <%= render 'form'%>
</div>

app/views/items/show.html.erb
<div class="show-page">
  <h2><%= @item.name %></h2>
  <%= link_to '<i class="arrow left icon"></i>Items'.html_safe, items_path %><br/>

  <%= show_image(@item) %>

  <table id="index" class="ui red striped celled table">
    <thead>
      <tr>
        <th>Type</th>
        <th>Description</th>
        <th>Updated</th>
        <th>Options</th>
      </tr>
    </thead>
    <tr>
      <td><%= @item.item_type %></td>
      <td><%= @item.item_description %></td>
      <td><%= @item.updated_at.strftime('%m-%d-%Y') %></td>
      <td>
          <%= link_to 'Edit', edit_item_path(@item), class: 'ui primary basic button'%>
          <%= link_to 'Delete', delete_item_path(@item), class: 'ui negative basic button'%>
      </td>
    </tr>
  </table>
</div>